"""Pre-build hook: generate firmware/src/secrets/sealed_blobs.h from any
.sealed files committed under firmware/secrets/.

The generated header declares one byte array per sealed blob, plus its
length. App code includes the header and feeds the bytes through the
mbedTLS AES-GCM decryptor (services/sealed.cpp)."""

from pathlib import Path

Import("env")  # noqa: F821 — PlatformIO global

PROJECT_DIR = Path(env["PROJECT_DIR"])  # noqa: F821
SECRETS_DIR = PROJECT_DIR / "secrets"
OUT_HEADER  = PROJECT_DIR / "src" / "secrets" / "sealed_blobs.h"

KNOWN_BLOBS = {
    "ssh_hosts.sealed": ("kSshHostsSealed", "kSshHostsSealedLen"),
    "github_pat.sealed": ("kGithubPatSealed", "kGithubPatSealedLen"),
}


def emit_array(name: str, length_name: str, data: bytes, out) -> None:
    out.write(f"// {name}: {len(data)} bytes\n")
    out.write(f"constexpr size_t {length_name} = {len(data)};\n")
    out.write(f"constexpr uint8_t {name}[{max(1, len(data))}] = {{")
    if data:
        for i, b in enumerate(data):
            if i % 16 == 0:
                out.write("\n    ")
            out.write(f"0x{b:02x},")
    else:
        out.write("0x00")
    out.write("\n};\n\n")


def main() -> None:
    OUT_HEADER.parent.mkdir(parents=True, exist_ok=True)
    with OUT_HEADER.open("w") as out:
        out.write("// Auto-generated by scripts/embed_secrets.py — do not edit.\n")
        out.write("// Each blob is AES-256-GCM ciphertext as: nonce(12) || ct || tag(16).\n")
        out.write("// Decryption key comes from identity::sealKey() (per-device NVS).\n\n")
        out.write("#pragma once\n\n")
        out.write("#include <cstddef>\n")
        out.write("#include <cstdint>\n\n")

        for filename, (name, length_name) in KNOWN_BLOBS.items():
            path = SECRETS_DIR / filename
            if path.exists():
                data = path.read_bytes()
                print(f"  embed_secrets: {filename} ({len(data)} bytes)")
            else:
                data = b""
                print(f"  embed_secrets: {filename} absent — emitting stub")
            emit_array(name, length_name, data, out)


main()
