#include "sealed.h"

#include <Arduino.h>
#include <ArduinoJson.h>
#include <mbedtls/gcm.h>

#include "identity.h"

// Auto-generated by firmware/scripts/embed_secrets.py. Defines:
//   const uint8_t kSshHostsSealed[];
//   const size_t  kSshHostsSealedLen;
// When the .sealed file is absent the script still emits a stub with zero
// length so the firmware compiles.
#include "secrets/sealed_blobs.h"

namespace {

// Storage arena for decrypted strings so SshHost.{name,host,user} pointers
// stay valid for the caller. Cleared on each unsealSshHosts() call.
std::string g_arena;
std::vector<std::string> g_strings;   // each entry is one C-string

const char* intern(const std::string& s) {
    g_strings.push_back(s);
    return g_strings.back().c_str();
}

}  // namespace

namespace sealed {

namespace {

// Generic AES-256-GCM decrypt helper for any sealed blob. Returns true on
// success and fills `out` with the plaintext bytes.
bool gcmDecrypt(const uint8_t* blob, size_t blobLen, std::vector<uint8_t>& out) {
    if (blobLen < 12 + 16) return false;
    const uint8_t* nonce = &blob[0];
    const uint8_t* ct    = &blob[12];
    size_t         ctLen = blobLen - 12 - 16;
    const uint8_t* tag   = &blob[12 + ctLen];

    out.assign(ctLen, 0);

    mbedtls_gcm_context gcm;
    mbedtls_gcm_init(&gcm);
    int rc = mbedtls_gcm_setkey(&gcm, MBEDTLS_CIPHER_ID_AES,
                                identity::sealKey(), 256);
    if (rc != 0) {
        Serial.printf("[sealed] gcm_setkey failed %d\n", rc);
        mbedtls_gcm_free(&gcm);
        return false;
    }
    rc = mbedtls_gcm_auth_decrypt(&gcm, ctLen,
                                  nonce, 12,
                                  nullptr, 0,
                                  tag, 16,
                                  ct, out.data());
    mbedtls_gcm_free(&gcm);
    if (rc != 0) {
        Serial.printf("[sealed] gcm_auth_decrypt failed %d (key mismatch?)\n", rc);
        return false;
    }
    return true;
}

}  // namespace

std::vector<SshHost> unsealSshHosts() {
    g_strings.clear();
    std::vector<SshHost> out;

    if (kSshHostsSealedLen == 0) {
        Serial.println("[sealed] no ssh_hosts.sealed embedded");
        return out;
    }

    std::vector<uint8_t> pt;
    if (!gcmDecrypt(kSshHostsSealed, kSshHostsSealedLen, pt)) {
        Serial.println("[sealed] ssh_hosts decrypt failed");
        return out;
    }

    JsonDocument doc;
    if (deserializeJson(doc, pt.data(), pt.size())) {
        Serial.println("[sealed] decrypted payload is not valid JSON");
        return out;
    }
    if (!doc.is<JsonArray>()) {
        Serial.println("[sealed] decrypted payload is not a JSON array");
        return out;
    }

    g_strings.reserve(doc.size() * 3);
    for (JsonObject obj : doc.as<JsonArray>()) {
        SshHost h;
        h.name = intern(obj["name"] | "");
        h.host = intern(obj["host"] | "");
        h.user = intern(obj["user"] | "");
        h.port = obj["port"] | 22;
        out.push_back(h);
    }
    return out;
}

std::string unsealGithubPat() {
    static std::string cached;
    static bool        attempted = false;
    if (attempted) return cached;
    attempted = true;

    if (kGithubPatSealedLen == 0) {
        Serial.println("[sealed] no github_pat.sealed embedded");
        return cached;
    }
    std::vector<uint8_t> pt;
    if (!gcmDecrypt(kGithubPatSealed, kGithubPatSealedLen, pt)) {
        Serial.println("[sealed] github_pat decrypt failed");
        return cached;
    }
    cached.assign((const char*)pt.data(), pt.size());
    while (!cached.empty() &&
           (cached.back() == '\n' || cached.back() == '\r' ||
            cached.back() == ' '  || cached.back() == '\t')) {
        cached.pop_back();
    }
    Serial.printf("[sealed] github_pat unsealed (%u chars)\n",
                  (unsigned)cached.size());
    return cached;
}

}  // namespace sealed
